apiVersion: skaffold/v2beta3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ishakantony/dirty-santa-game
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server.js"
            dest: .
          - src: "client/*.html"
            dest: .
          - src: "public/**/*.*"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/*
